# Generated by CMake 2.8.12.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget v4r_core v4r_io v4r_common v4r_features v4r_keypoints v4r_ml v4r_reconstruction v4r_registration v4r_rendering v4r_segmentation v4r_tracking v4r_object_modelling v4r_recognition)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target v4r_core
add_library(v4r_core SHARED IMPORTED)

# Create imported target v4r_io
add_library(v4r_io SHARED IMPORTED)

# Create imported target v4r_common
add_library(v4r_common SHARED IMPORTED)

# Create imported target v4r_features
add_library(v4r_features SHARED IMPORTED)

# Create imported target v4r_keypoints
add_library(v4r_keypoints SHARED IMPORTED)

# Create imported target v4r_ml
add_library(v4r_ml SHARED IMPORTED)

# Create imported target v4r_reconstruction
add_library(v4r_reconstruction SHARED IMPORTED)

# Create imported target v4r_registration
add_library(v4r_registration SHARED IMPORTED)

# Create imported target v4r_rendering
add_library(v4r_rendering SHARED IMPORTED)

# Create imported target v4r_segmentation
add_library(v4r_segmentation SHARED IMPORTED)

# Create imported target v4r_tracking
add_library(v4r_tracking SHARED IMPORTED)

# Create imported target v4r_object_modelling
add_library(v4r_object_modelling SHARED IMPORTED)

# Create imported target v4r_recognition
add_library(v4r_recognition SHARED IMPORTED)

# Import target "v4r_core" for configuration "Release"
set_property(TARGET v4r_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_core PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_core.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_core.so.1.0"
  )

# Import target "v4r_io" for configuration "Release"
set_property(TARGET v4r_io APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_io PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_io.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_io.so.1.0"
  )

# Import target "v4r_common" for configuration "Release"
set_property(TARGET v4r_common APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_common PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_common.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_common.so.1.0"
  )

# Import target "v4r_features" for configuration "Release"
set_property(TARGET v4r_features APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_features PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_common;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_features.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_features.so.1.0"
  )

# Import target "v4r_keypoints" for configuration "Release"
set_property(TARGET v4r_keypoints APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_keypoints PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_common;v4r_features;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_keypoints.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_keypoints.so.1.0"
  )

# Import target "v4r_ml" for configuration "Release"
set_property(TARGET v4r_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_ml PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/libsvm.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_ml.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_ml.so.1.0"
  )

# Import target "v4r_reconstruction" for configuration "Release"
set_property(TARGET v4r_reconstruction APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_reconstruction PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ceres;opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;v4r_features;v4r_keypoints;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_reconstruction.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_reconstruction.so.1.0"
  )

# Import target "v4r_registration" for configuration "Release"
set_property(TARGET v4r_registration APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_registration PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ceres;opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;v4r_features;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_registration.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_registration.so.1.0"
  )

# Import target "v4r_rendering" for configuration "Release"
set_property(TARGET v4r_rendering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_rendering PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_common;/usr/lib/libassimp.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/local/lib64/libGLEW.so;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_rendering.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_rendering.so.1.0"
  )

# Import target "v4r_segmentation" for configuration "Release"
set_property(TARGET v4r_segmentation APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_segmentation PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_segmentation.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_segmentation.so.1.0"
  )

# Import target "v4r_tracking" for configuration "Release"
set_property(TARGET v4r_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_tracking PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ceres;opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;v4r_features;v4r_keypoints;v4r_reconstruction;v4r_registration;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_tracking.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_tracking.so.1.0"
  )

# Import target "v4r_object_modelling" for configuration "Release"
set_property(TARGET v4r_object_modelling APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_object_modelling PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ceres;opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;v4r_features;v4r_keypoints;v4r_registration;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_object_modelling.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_object_modelling.so.1.0"
  )

# Import target "v4r_recognition" for configuration "Release"
set_property(TARGET v4r_recognition APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(v4r_recognition PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ceres;opencv_videostab;opencv_video;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d;vtkCommon;vtkFiltering;vtkImaging;vtkGraphics;vtkGenericFiltering;vtkIO;vtkRendering;vtkVolumeRendering;vtkHybrid;vtkWidgets;vtkParallel;vtkInfovis;vtkGeovis;vtkViews;vtkCharts"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "v4r_core;v4r_io;v4r_common;v4r_features;v4r_keypoints;v4r_registration;v4r_rendering;v4r_segmentation;/usr/lib/libassimp.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/local/lib64/libGLEW.so;/usr/lib/x86_64-linux-gnu/libglog.so;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/libpcl_common.so;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/x86_64-linux-gnu/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libOpenNI.so;/opt/ros/indigo/lib/libOpenNI2.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;GLEW;IL"
  IMPORTED_LOCATION_RELEASE "/home/thomas/Projects/v4r_git/build_clang/lib/libv4r_recognition.so.1.0.0"
  IMPORTED_SONAME_RELEASE "libv4r_recognition.so.1.0"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
