if(WITH_CAFFE)
  find_package(Caffe)
  if(Caffe_FOUND)
    set(CAFFE_LIBRARIES "${Caffe_LIBRARIES}")
    set(CAFFE_INCLUDE_DIRS "${Caffe_INCLUDE_DIRS}")
    add_definitions(${Caffe_DEFINITIONS})
    set(HAVE_CAFFE TRUE)
  endif()
endif()
