#if(WITH_XRANDR)
#  find_package(XRANDR)
#  if(XRANDR_FOUND)
#    message("********ASDFSAFSAFSDAFSDAF***********")
#    set(XRANDR_LIBRARIES "${XRandr_LIBRARIES}")
#    set(XRANDR_INCLUDE_DIRS "${XRandr_INCLUDE_DIR}")
#    set(HAVE_XRANDR TRUE)
#  endif()
#endif()
