if(WITH_CERES)
  find_package(Ceres)
  if(${Ceres_FOUND})
    set(CERES_LIBRARIES "${CERES_LIBRARIES}")
    set(CERES_INCLUDE_DIRS "${CERES_INCLUDES}")
    set(HAVE_CERES TRUE)
    IF(${Ceres_VERSION} EQUAL 1.8.0)
     add_definitions(-DCERES_VERSION_LESS_1_9_0)
    ENDIF(${Ceres_VERSION} EQUAL 1.8.0)
  endif()
endif()
