if(WITH_CAFFE)
  find_package(Caffe)
  if(Caffe_FOUND)
    get_target_property(CAFFE_INCLUDE_DIRS caffe INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(CAFFE_DEFINITIONS caffe INTERFACE_COMPILE_DEFINITIONS)
    set(CAFFE_LIBRARIES "${Caffe_LIBRARIES}")
    add_definitions(${Caffe_DEFINITIONS})
    set(HAVE_CAFFE TRUE)
  endif()
endif()
