if(WITH_EDT)
  if(BUILD_EDT)
    v4r_clear_vars(EDT_FOUND)
  endif()
  if(NOT EDT_FOUND)
    v4r_clear_vars(EDT_LIBRARY EDT_LIBRARIES EDT_INCLUDE_DIRS)
    set(EDT_LIBRARY edt)
    set(EDT_LIBRARIES ${EDT_LIBRARY})
    add_subdirectory("${V4R_SOURCE_DIR}/3rdparty/EDT")
    set(EDT_INCLUDE_DIRS "${V4R_SOURCE_DIR}/3rdparty")
    #set(EDT_DEFINITIONS "")
  endif()
  set(HAVE_EDT YES)
endif()
