if(WITH_ON_NURBS)
  if(BUILD_ON_NURBS)
    v4r_clear_vars(ON_NURBS_FOUND)
  endif()
  if(NOT ON_NURBS_FOUND)
    v4r_clear_vars(ON_NURBS_LIBRARY ON_NURBS_INCLUDE_DIRS ON_NURBS_VERSION)
    set(ON_NURBS_LIBRARY on_nurbs)
    Set(ON_NURBS_LIBRARIES ${ON_NURBS_LIBRARY})
    add_subdirectory("${V4R_SOURCE_DIR}/3rdparty/on_nurbs")
    set(ON_NURBS_INCLUDE_DIRS "${V4R_SOURCE_DIR}/3rdparty")
    set(ON_NURBS_VERSION "1.0") # TODO
  endif()
  set(HAVE_ON_NURBS YES)
endif()
