if(WITH_SIFTGPU)
  if(BUILD_SIFTGPU)
    v4r_clear_vars(SIFTGPU_FOUND)
  endif()
  if(NOT SIFTGPU_FOUND)
    v4r_clear_vars(SIFTGPU_LIBRARY SIFTGPU_INCLUDE_DIR)
    set(SIFTGPU_LIBRARY siftgpu)
    #set(EDT_LIBRARIES ${EDT_LIBRARY})
    add_subdirectory("${V4R_SOURCE_DIR}/3rdparty/SiftGPU")
    #set(EDT_INCLUDE_DIR "${${EDT_LIBRARY}_SOURCE_DIR}")
    #set(EDT_DEFINITIONS "")
  endif()
  set(SIFTGPU_VERSION "v400")
  set(HAVE_SIFTGPU YES)
endif()
